import { useEffect, useState } from "react";
import { useProjectsChangedTick } from "./projectEvents";
import { sfetch, setProjectScope } from "./projectScope";
import { formatDataDate, sourceDataDateTooltip, versionSelectLabel, dedupeVersionsById } from "./dateFormat";

const C = {
  bg: "#f5f2ec", panel: "#ede9df", card: "#ffffff", card2: "#f0ece4",
  border: "#d4ccc0", accent: "#d97000", gold: "#b89200", green: "#00936b",
  amber: "#c47c00", red: "#d93030", purple: "#7c3aed", orange: "#c85000",
  text: "#1c1410", muted: "#7a6454", muted2: "#a08870",
};
const API = "";

function Select({ value, onChange, options, placeholder }: any) {
  return (
    <select value={value} onChange={e => onChange(e.target.value)}
      style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 7, padding: "6px 10px", fontSize: 12, fontFamily: "inherit", color: C.text, minWidth: 150 }}>
      {placeholder && <option value="">{placeholder}</option>}
      {options.map((o: any) => <option key={o.value} value={o.value}>{o.label}</option>)}
    </select>
  );
}

const REPORT_TEMPLATES = [
  { value: "weekly", label: "Weekly Schedule Report" },
  { value: "executive", label: "Executive Schedule Report" },
  { value: "health", label: "Schedule Health Report" },
  { value: "comparison", label: "Update Comparison Report" },
  { value: "risk", label: "Risk Report" },
];

function esc(s: any): string {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildReportHTML(templateLabel: string, project: any, version: any, sections: { title: string; html: string }[]): string {
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const body = sections.map(s => `<h2>${esc(s.title)}</h2>${s.html}`).join("\n");
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${esc(templateLabel)} — ${esc(project?.name)}</title>
<style>
  @media print{@page{margin:2cm;size:A4}body{font-size:10pt}}
  body{font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#111;padding:20px}
  h1{font-size:18pt;margin-bottom:2px}
  h2{font-family:Calibri,Arial,sans-serif;font-size:13pt;color:#1a3a5c;border-bottom:1px solid #ccc;padding-bottom:4px;margin-top:22px}
  table{border-collapse:collapse;width:100%;margin:8px 0}
  th,td{border:1px solid #ccc;padding:5px 8px;font-size:9.5pt;text-align:left}
  th{background:#1a3a5c;color:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  tr:nth-child(even){background:#f8f9fa;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .meta{color:#555;font-size:10pt;margin-bottom:14px}
  .footer{color:#555;font-size:9pt;margin-top:24px;border-top:1px solid #e0e0e0;padding-top:8px}
</style></head><body>
<h1>${esc(templateLabel)}</h1>
<div class="meta">
  <strong>${esc(project?.name)}</strong>${project?.projectNumber ? ` (${esc(project.projectNumber)})` : ""}<br/>
  Schedule Version: ${esc(version?.versionLabel)} · Data Date: ${esc(formatDataDate(version?.dataDate))}${version?.dataDateOverridden ? ` · Overridden (${esc(sourceDataDateTooltip(version) || "")})` : ""}<br/>
  Generated: ${today}
</div>
${body}
<div class="footer">Auto-generated by ScheduleIQ from calculated schedule data on ${today}. Results should be reviewed by the project scheduling team before formal issuance.</div>
<script>window.onload=function(){window.print();}<\/script>
</body></html>`;
}

function printHTML(html: string) {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}

export default function Reports() {
  const [projects, setProjects] = useState<any[]>([]);
  const projectsTick = useProjectsChangedTick();
  const [projectId, setProjectId] = useState("");
  setProjectScope(projectId);   // stale responses from a previously selected project are dropped (see projectScope.ts)
  const [versions, setVersions] = useState<any[]>([]);
  const [versionId, setVersionId] = useState("");
  const [compareVersionId, setCompareVersionId] = useState("");
  const [template, setTemplate] = useState("executive");
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { fetch(`${API}/api/projects/?withVersions=true`).then(r => r.json()).then(d => { const list = d.projects || []; setProjects(list); setProjectId((cur: string) => (cur && !list.some((p: any) => p.id === cur) ? "" : cur)); }).catch(() => {}); }, [projectsTick]);
  useEffect(() => {
    if (!projectId) { setVersions([]); return; }
    sfetch(`${API}/api/projects/${projectId}/versions/`).then(r => r.json()).then(d => {
      const vs = d.versions || [];
      setVersions(dedupeVersionsById(vs));
      const cur = vs.find((v: any) => v.role === "CURRENT");
      const prev = vs.find((v: any) => v.role === "PREVIOUS");
      setVersionId(cur?.id || vs[0]?.id || "");
      setCompareVersionId(prev?.id || "");
    }).catch(() => setVersions([]));
  }, [projectId, projectsTick]);

  const generate = async () => {
    setGenerating(true); setError(null);
    try {
      const project = projects.find(p => p.id === projectId);
      const version = versions.find(v => v.id === versionId);
      const templateLabel = REPORT_TEMPLATES.find(t => t.value === template)?.label || "Schedule Report";
      const sections: { title: string; html: string }[] = [];

      const riskResp = await sfetch(`${API}/api/projects/${projectId}/risk/?version=${versionId}`).then(r => r.json());
      const milestonesResp = await sfetch(`${API}/api/projects/${projectId}/milestones/?version=${versionId}`).then(r => r.json());

      let compareResp: any = null;
      if (compareVersionId && (template === "comparison" || template === "weekly" || template === "executive")) {
        compareResp = await sfetch(`${API}/api/projects/${projectId}/compare/`, {
          method: "POST", headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ previousVersionId: compareVersionId, currentVersionId: versionId, pageSize: 20 }),
        }).then(r => r.json());
      }

      // Executive summary
      sections.push({
        title: "Executive Summary",
        html: `<p>Overall schedule risk score is <strong>${riskResp.overall.score}</strong> (${riskResp.overall.level}). ` +
          `${milestonesResp.milestoneCount} milestones tracked. ` +
          (compareResp ? esc(compareResp.summaryNarrative) : "No comparison version selected for this report.") + `</p>`,
      });

      // Schedule health / risk
      sections.push({
        title: "Schedule Risk",
        html: `<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>` +
          `<tr><td>Overall Score</td><td>${riskResp.overall.score} (${riskResp.overall.level})</td></tr>` +
          `<tr><td>Affected Activities</td><td>${riskResp.overall.affectedActivityCount} of ${riskResp.overall.totalActivityCount}</td></tr>` +
          riskResp.overall.drivers.map((d: any) => `<tr><td>${esc(d.type.replace(/_/g, " "))}</td><td>+${d.impact} (${d.count ?? ""})</td></tr>`).join("") +
          `</tbody></table>`,
      });

      // Milestones
      const msRows = milestonesResp.milestones.slice(0, 25).map((m: any) =>
        `<tr><td>${esc(m.activityId)}</td><td>${esc(m.activityName)}</td><td>${esc(m.currentFinish)}</td><td>${m.varianceDays ?? "—"}</td><td>${esc(m.riskLevel)}</td></tr>`
      ).join("");
      sections.push({
        title: "Milestones",
        html: `<table><thead><tr><th>ID</th><th>Name</th><th>Finish</th><th>Variance (d)</th><th>Risk</th></tr></thead><tbody>${msRows || "<tr><td colspan=5>No milestones.</td></tr>"}</tbody></table>`,
      });

      if (compareResp) {
        sections.push({
          title: "Update Comparison Summary",
          html: `<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>` +
            Object.entries(compareResp.summary).map(([k, v]) => `<tr><td>${esc(k.replace(/([A-Z])/g, " $1"))}</td><td>${esc(v)}</td></tr>`).join("") +
            `</tbody></table><p>${esc(compareResp.summaryNarrative)}</p>`,
        });

        const negFloatChanges = compareResp.changes.filter((c: any) => c.fieldKey === "totalFloat").slice(0, 15);
        sections.push({
          title: "Top Float Changes",
          html: `<table><thead><tr><th>Activity ID</th><th>Name</th><th>Previous</th><th>Current</th><th>Delta</th></tr></thead><tbody>` +
            (negFloatChanges.map((c: any) => `<tr><td>${esc(c.activityId)}</td><td>${esc(c.activityName)}</td><td>${c.previous}</td><td>${c.current}</td><td>${c.delta}</td></tr>`).join("") || "<tr><td colspan=5>No float changes.</td></tr>") +
            `</tbody></table>`,
        });
      }

      printHTML(buildReportHTML(templateLabel, project, version, sections));
    } catch (e: any) {
      setError(e.message || String(e));
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <div style={{ fontSize: 18, fontWeight: 800, color: C.text, marginBottom: 4 }}>Reports</div>
      <div style={{ fontSize: 13, color: C.muted, marginBottom: 14 }}>
        Every figure below is pulled live from ScheduleIQ's calculated data — nothing is fabricated. Opens a print-ready window (Save as PDF from your browser's print dialog).
      </div>

      <div style={{ display: "flex", flexWrap: "wrap", gap: 10, alignItems: "center", background: C.card2, border: `1px solid ${C.border}`, borderRadius: 10, padding: "12px 14px", marginBottom: 16 }}>
        <Select value={template} onChange={setTemplate} options={REPORT_TEMPLATES} />
        <div>
          <div style={{ fontSize: 10, color: C.muted, marginBottom: 3, textTransform: "uppercase" }}>Project</div>
          <Select value={projectId} onChange={(id: string) => { setVersions([]); setVersionId(""); setCompareVersionId(""); setProjectId(id); }} placeholder="Select a project…" options={projects.map((p: any) => ({ value: p.id, label: p.name }))} />
        </div>
        {projectId && versions.length > 0 && (
          <>
            <div>
              <div style={{ fontSize: 10, color: C.muted, marginBottom: 3, textTransform: "uppercase" }}>Version</div>
              <Select value={versionId} onChange={setVersionId} options={versions.map((v: any) => ({ value: v.id, label: versionSelectLabel(v) }))} />
            </div>
            <div>
              <div style={{ fontSize: 10, color: C.muted, marginBottom: 3, textTransform: "uppercase" }}>Compare To (optional)</div>
              <Select value={compareVersionId} onChange={setCompareVersionId} placeholder="None" options={versions.filter((v: any) => v.id !== versionId).map((v: any) => ({ value: v.id, label: versionSelectLabel(v) }))} />
            </div>
          </>
        )}
        <button onClick={generate} disabled={!versionId || generating}
          style={{ background: C.accent, border: "none", color: "#fff", borderRadius: 7, padding: "7px 20px", cursor: "pointer", fontSize: 12, fontWeight: 700, fontFamily: "inherit" }}>
          {generating ? "Generating…" : "Generate Report"}
        </button>
      </div>

      {error && <div style={{ color: C.red }}>⚠ {error}</div>}
      {!projectId && <div style={{ textAlign: "center", color: C.muted, padding: 60 }}>Select a project above, choose a report template, then generate.</div>}
    </div>
  );
}
