from django.urls import path

from .auth_views import csrf_bootstrap, login_view, logout_view, me_view, user_detail, users_list
from .views import (
    analyze,
    import_commit,
    import_preview,
    metrics,
    narrative,
    project_activity_analysis,
    project_ai_chat,
    project_ai_review,
    project_baseline_progress,
    project_baseline_progress_export,
    project_lookahead,
    project_compare,
    project_controls_drivers,
    project_controls_trends,
    project_cost_entries,
    project_cost_entry_detail,
    project_cost_history,
    project_cost_summary,
    project_detail,
    project_documents,
    project_earned_value,
    project_executive_summary,
    project_float_analysis,
    project_float_trend,
    project_dashboard_summary,
    project_milestones,
    project_productivity,
    project_report_detail,
    project_report_excel,
    project_report_pdf,
    project_reports,
    project_reports_compare,
    project_progress_curve,
    project_update_intelligence,
    project_recovery_scenario_detail,
    project_recovery_scenarios,
    project_risk,
    project_risk_register,
    project_risk_detail,
    project_risk_driving_chain,
    project_mitigation_actions,
    project_mitigation_action_detail,
    project_issues,
    project_issue_detail,
    project_contractual_milestones,
    project_contractual_milestone_detail,
    project_contractual_milestone_revisions,
    project_field_dashboard_summary,
    project_version_detail,
    project_version_restore,
    project_deleted_versions,
    project_versions,
    projects,
    projects_reconcile,
    projects_consolidation_plan,
    projects_consolidation_apply,
    projects_consolidation_simulate,
    version_difference_report,
    quality,
    threshold_profile_detail,
    threshold_profiles,
    upload,
)

urlpatterns = [
    path('auth/csrf/', csrf_bootstrap, name='auth_csrf'),
    path('auth/login/', login_view, name='auth_login'),
    path('auth/logout/', logout_view, name='auth_logout'),
    path('auth/me/', me_view, name='auth_me'),
    path('auth/users/', users_list, name='auth_users'),
    path('auth/users/<int:user_id>/', user_detail, name='auth_user_detail'),
    path('upload/', upload, name='upload'),
    path('metrics/', metrics, name='metrics'),
    path('analyze/', analyze, name='analyze'),
    path('quality/', quality, name='quality'),
    path('narrative/', narrative, name='narrative'),
    path('threshold-profiles/', threshold_profiles, name='threshold_profiles'),
    path('threshold-profiles/<str:pk>/', threshold_profile_detail, name='threshold_profile_detail'),
    path('import/preview/', import_preview, name='import_preview'),
    path('import/commit/', import_commit, name='import_commit'),
    path('projects/', projects, name='projects'),
    path('projects/reconcile/', projects_reconcile, name='projects_reconcile'),
    path('projects/consolidation-plan/', projects_consolidation_plan, name='projects_consolidation_plan'),
    path('projects/consolidation-apply/', projects_consolidation_apply, name='projects_consolidation_apply'),
    path('projects/consolidation-simulate/', projects_consolidation_simulate, name='projects_consolidation_simulate'),
    path('projects/version-difference-report/', version_difference_report, name='version_difference_report'),
    path('projects/<str:pk>/', project_detail, name='project_detail'),
    path('projects/<str:pk>/versions/', project_versions, name='project_versions'),
    path('projects/<str:pk>/activity-analysis/', project_activity_analysis, name='project_activity_analysis'),
    path('projects/<str:pk>/float-analysis/', project_float_analysis, name='project_float_analysis'),
    path('projects/<str:pk>/float-trend/', project_float_trend, name='project_float_trend'),
    path('projects/<str:pk>/dashboard-summary/', project_dashboard_summary, name='project_dashboard_summary'),
    # Must be registered BEFORE versions/<str:version_id>/ below, or that
    # pattern would greedily treat "deleted" as a version_id.
    path('projects/<str:pk>/versions/deleted/', project_deleted_versions, name='project_deleted_versions'),
    path('projects/<str:pk>/versions/<str:version_id>/', project_version_detail, name='project_version_detail'),
    path('projects/<str:pk>/versions/<str:version_id>/restore/', project_version_restore, name='project_version_restore'),
    path('projects/<str:pk>/documents/', project_documents, name='project_documents'),
    path('projects/<str:pk>/compare/', project_compare, name='project_compare'),
    path('projects/<str:pk>/progress-curve/', project_progress_curve, name='project_progress_curve'),
    path('projects/<str:pk>/risk/', project_risk, name='project_risk'),
    path('projects/<str:pk>/milestones/', project_milestones, name='project_milestones'),
    path('projects/<str:pk>/baseline-progress/', project_baseline_progress, name='project_baseline_progress'),
    path('projects/<str:pk>/baseline-progress/export/', project_baseline_progress_export, name='project_baseline_progress_export'),
    path('projects/<str:pk>/lookahead/', project_lookahead, name='project_lookahead'),
    path('projects/<str:pk>/update-intelligence/', project_update_intelligence, name='project_update_intelligence'),
    path('projects/<str:pk>/ai-review/', project_ai_review, name='project_ai_review'),
    path('projects/<str:pk>/ai-chat/', project_ai_chat, name='project_ai_chat'),
    path('projects/<str:pk>/recovery-scenarios/', project_recovery_scenarios, name='project_recovery_scenarios'),
    path('projects/<str:pk>/recovery-scenarios/<str:scenario_id>/', project_recovery_scenario_detail, name='project_recovery_scenario_detail'),
    path('projects/<str:pk>/risk-register/', project_risk_register, name='project_risk_register'),
    path('projects/<str:pk>/risk-register/<str:risk_key>/', project_risk_detail, name='project_risk_detail'),
    path('projects/<str:pk>/risk-register/<str:risk_key>/driving-chain/', project_risk_driving_chain, name='project_risk_driving_chain'),
    path('projects/<str:pk>/mitigation-actions/', project_mitigation_actions, name='project_mitigation_actions'),
    path('projects/<str:pk>/mitigation-actions/<str:action_id>/', project_mitigation_action_detail, name='project_mitigation_action_detail'),
    path('projects/<str:pk>/issues/', project_issues, name='project_issues'),
    path('projects/<str:pk>/issues/<str:issue_id>/', project_issue_detail, name='project_issue_detail'),
    path('projects/<str:pk>/contractual-milestones/', project_contractual_milestones, name='project_contractual_milestones'),
    path('projects/<str:pk>/contractual-milestones/<str:milestone_id>/', project_contractual_milestone_detail, name='project_contractual_milestone_detail'),
    path('projects/<str:pk>/contractual-milestones/<str:milestone_id>/revisions/', project_contractual_milestone_revisions, name='project_contractual_milestone_revisions'),
    path('projects/<str:pk>/field-dashboard-summary/', project_field_dashboard_summary, name='project_field_dashboard_summary'),
    path('projects/<str:pk>/cost-summary/', project_cost_summary, name='project_cost_summary'),
    path('projects/<str:pk>/earned-value/', project_earned_value, name='project_earned_value'),
    path('projects/<str:pk>/productivity/', project_productivity, name='project_productivity'),
    path('projects/<str:pk>/cost-history/', project_cost_history, name='project_cost_history'),
    path('projects/<str:pk>/controls-trends/', project_controls_trends, name='project_controls_trends'),
    path('projects/<str:pk>/controls-drivers/', project_controls_drivers, name='project_controls_drivers'),
    path('projects/<str:pk>/executive-summary/', project_executive_summary, name='project_executive_summary'),
    path('projects/<str:pk>/reports/compare/', project_reports_compare, name='project_reports_compare'),
    path('projects/<str:pk>/reports/', project_reports, name='project_reports'),
    path('projects/<str:pk>/reports/<str:report_id>/', project_report_detail, name='project_report_detail'),
    path('projects/<str:pk>/reports/<str:report_id>/pdf/', project_report_pdf, name='project_report_pdf'),
    path('projects/<str:pk>/reports/<str:report_id>/excel/', project_report_excel, name='project_report_excel'),
    path('projects/<str:pk>/cost-entries/', project_cost_entries, name='project_cost_entries'),
    path('projects/<str:pk>/cost-entries/<str:entry_id>/', project_cost_entry_detail, name='project_cost_entry_detail'),
]
