# Generated by Django 5.2.17 on 2026-08-09 16:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('project_number', models.CharField(blank=True, max_length=100)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='duplicate_activity_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='invalid_date_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='mapped_columns',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='unmapped_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='scheduler.project'),
        ),
    ]
