# Generated by Django 5.2.17 on 2026-08-09 16:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_project_scheduleupload_duplicate_activity_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleupload',
            name='avg_total_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='critical_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='import_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='in_progress_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='max_total_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='milestone_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='min_total_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='negative_float_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='not_started_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='parser_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='version_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ActivityCodeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_type_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_global', models.BooleanField(default=False)),
                ('schedule_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_code_types', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(max_length=50)),
                ('code_value', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('parent_code_id', models.CharField(blank=True, max_length=50)),
                ('code_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='scheduler.activitycodetype')),
            ],
            options={
                'ordering': ['code_value'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('calendar_type', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('hours_per_day', models.FloatField(blank=True, null=True)),
                ('hours_per_week', models.FloatField(blank=True, null=True)),
                ('hours_per_month', models.FloatField(blank=True, null=True)),
                ('hours_per_year', models.FloatField(blank=True, null=True)),
                ('standard_workweek', models.JSONField(blank=True, default=dict)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('has_detailed_definition', models.BooleanField(default=False)),
                ('raw_definition', models.TextField(blank=True)),
                ('schedule_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UDFType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('udf_type_id', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=200)),
                ('subject_area', models.CharField(blank=True, max_length=50)),
                ('data_type', models.CharField(blank=True, max_length=50)),
                ('schedule_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udf_types', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(choices=[('SCHEDULE_NARRATIVE', 'Schedule Narrative'), ('LOOKAHEAD', 'Lookahead'), ('OWNER_REPORT', 'Owner Report'), ('CONTRACTOR_REPORT', 'Contractor Report'), ('SCHEDULE_TABLE', 'Schedule Table'), ('GENERAL_ATTACHMENT', 'General Attachment')], default='GENERAL_ATTACHMENT', max_length=30)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('extraction_warnings', models.JSONField(default=list)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scheduler.project')),
                ('schedule_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['project'], name='scheduler_s_project_4a4d80_idx'), models.Index(fields=['document_type'], name='scheduler_s_documen_43190e_idx')],
            },
        ),
    ]
