# Generated by Django 5.2.17 on 2026-08-09 17:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduleupload_avg_total_float_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assumptions', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_scenarios', to='scheduler.project')),
                ('schedule_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_scenarios', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
