# Generated by Django 5.2.17 on 2026-08-14 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_recoveryscenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('wbs_id', models.CharField(blank=True, max_length=50)),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('system', models.CharField(blank=True, max_length=200)),
                ('cost_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_accounts', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='ManualCostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('APPROVED_BUDGET_CHANGE', 'Approved Budget Change'), ('ORIGINAL_BUDGET_OVERRIDE', 'Original Budget Override'), ('COMMITMENT', 'Commitment (PO / Subcontract)'), ('APPROVED_EAC', 'Approved Estimate at Completion')], max_length=30)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('wbs_id', models.CharField(blank=True, max_length=50)),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('system', models.CharField(blank=True, max_length=200)),
                ('cost_code', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('entered_by', models.CharField(blank=True, max_length=200)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='scheduler.costaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_cost_entries', to='scheduler.project')),
                ('schedule_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_cost_entries', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
    ]
