# Generated by Django 5.2.17 on 2026-08-15 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_costaccount_manualcostentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectControlsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_date', models.DateField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('WEEKLY_PROJECT_CONTROLS', 'Weekly Project Controls Report'), ('MONTHLY_EXECUTIVE', 'Monthly Executive Report')], max_length=30)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload_json', models.JSONField(default=dict)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('ev_method', models.CharField(blank=True, max_length=40)),
                ('pv_method', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('ARCHIVED', 'Archived')], default='GENERATED', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls_reports', to='scheduler.project')),
                ('schedule_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_reports', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['project', 'report_type'], name='scheduler_p_project_663937_idx'), models.Index(fields=['generated_at'], name='scheduler_p_generat_5852b0_idx')],
            },
        ),
    ]
