# Generated by Django 5.2.17 on 2026-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_projectcontrolsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleupload',
            name='data_date_confidence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='data_date_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='data_date_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='source_data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
