# Generated by Django 5.2.17 on 2026-09-22 13:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_scheduleupload_data_date_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryscenario',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduleRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('MITIGATION_PLANNED', 'Mitigation Planned'), ('MITIGATION_IN_PROGRESS', 'Mitigation In Progress'), ('MONITORING', 'Monitoring'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('mitigation_notes', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('first_identified_data_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_identified_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduler.scheduleupload')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_risks', to='scheduler.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MitigationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='scheduler.project')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='scheduler.recoveryscenario')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='scheduler.schedulerisk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recoveryscenario',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_scenarios', to='scheduler.schedulerisk'),
        ),
        migrations.AddIndex(
            model_name='schedulerisk',
            index=models.Index(fields=['project', 'risk_key'], name='scheduler_s_project_a5d8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerisk',
            index=models.Index(fields=['project', 'status'], name='scheduler_s_project_6f2c3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulerisk',
            unique_together={('project', 'risk_key')},
        ),
        migrations.AddIndex(
            model_name='mitigationaction',
            index=models.Index(fields=['project', 'status'], name='scheduler_m_project_de230a_idx'),
        ),
    ]
