# Generated by Django 5.2.17 on 2026-10-01 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_recoveryscenario_status_schedulerisk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonedefinition',
            name='source_document_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ContractualMilestoneRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('source_document_reference', models.CharField(blank=True, max_length=500)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scheduler.milestonedefinition')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
