# Generated by Django 5.2.17 on 2026-10-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_milestonedefinition_source_document_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonedefinition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractual_milestones', to='scheduler.project'),
        ),
    ]
