# Generated by Django 5.2.17 on 2026-10-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_milestonedefinition_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonedefinition',
            name='has_documented_issue',
            field=models.BooleanField(default=False),
        ),
    ]
