# Generated by Django 5.2.17 on 2026-10-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_milestonedefinition_has_documented_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('REFUSED', 'Refused (validation/confirmation not satisfied)'), ('FAILED', 'Failed (unexpected error)'), ('UNAUTHORIZED', 'Unauthorized')], default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='content_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='scheduler_a_request_3c417e_idx'),
        ),
    ]
