# Generated by Django 5.2.17 on 2026-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleupload',
            name='xer_additional_project_record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='xer_additional_project_records',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleupload',
            name='xer_project_record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
