# Generated by Django 5.2.17 on 2026-10-05 19:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_scheduleupload_xer_additional_project_record_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('PROCUREMENT', 'Procurement'), ('CONSTRUCTION', 'Construction'), ('PREFABRICATION', 'Prefabrication'), ('EQUIPMENT_DELIVERY', 'Equipment Delivery'), ('QA_QC', 'QA/QC'), ('COMMISSIONING', 'Commissioning'), ('PRODUCTIVITY', 'Productivity'), ('MANPOWER', 'Manpower'), ('DESIGN_COORDINATION', 'Design/Coordination'), ('OWNER_GC', 'Owner/GC'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MONITORING', 'Monitoring'), ('MITIGATING', 'Mitigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('date_identified', models.DateField(default=django.utils.timezone.localdate)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('required_action', models.TextField(blank=True)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('actual_resolution_date', models.DateField(blank=True, null=True)),
                ('schedule_impact', models.BooleanField(default=False)),
                ('cost_impact', models.BooleanField(default=False)),
                ('affected_area', models.CharField(blank=True, max_length=300)),
                ('linked_activity_ids', models.JSONField(blank=True, default=list)),
                ('source_reference', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_issues', to='scheduler.milestonedefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='scheduler.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='scheduler.projectissue'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['project', 'status'], name='scheduler_p_project_45c16a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['project', 'severity'], name='scheduler_p_project_d20dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectissue',
            unique_together={('project', 'issue_number')},
        ),
    ]
