# Generated by Django 5.2.17 on 2026-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_projectissue_mitigationaction_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_issue_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
