# Generated by Django 5.2.17 on 2026-10-08 20:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_project_next_issue_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFieldReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('actual_headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('next_week_forecast_headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('pm_projected_headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_target_headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('last_client_update_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_field_reports', to='scheduler.project')),
                ('schedule_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_field_reports', to='scheduler.scheduleupload')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'indexes': [models.Index(fields=['project', 'week_start_date'], name='scheduler_w_project_5c53e5_idx')],
                'unique_together': {('project', 'week_start_date')},
            },
        ),
    ]
